site_name: egov4dev
site_url: https://egov-moldova.github.io/egov4dev/

nav:
  - Home: index.md
  - Platforms and services: platforms/services.md
  - Development principles: principles/architecture.md
  - Tools and technologies: tools/technologies.md
  - Glossary: glossary/glossary.md
  - Integration guides:
      - MPass: 
          - Overview: guides/mpass/index.md
          - Steps to connect: guides/mpass/process.md
          - Interaction scenarios: guides/mpass/interaction-scenarios.md
          - Integration development: guides/mpass/integration-development.md
          - Integration tests: guides/mpass/integration-tests.md
          - API references: guides/mpass/api-references.md
          - Examples: guides/mpass/examples.md
          - Integration libraries: guides/mpass/integration-libraries.md
          - Change log: guides/mpass/change-log.md
      - MSign:
          - Overview: guides/msign/index.md
          - Steps to connect: guides/msign/process.md
          - Interaction scenarios: guides/msign/interaction-scenarios.md
          - Integration development: guides/msign/integration-development.md
          - API references: guides/msign/api-references.md
          - Examples: guides/msign/examples.md
          - Integration libraries: guides/msign/integration-libraries.md
          - Change log: guides/msign/change-log.md
      - MPower:
          - Overview: guides/mpower/index.md
          - Steps to connect: guides/mpower/process.md
          - Interaction scenarios: guides/mpower/interaction-scenarios.md
          - Integration development: guides/mpower/integration-development.md
          - Security: guides/mpower/security.md
          - API references: guides/mpower/api-references.md
          - Change log: guides/mpower/change-log.md
      - MPay:
          - Overview: guides/mpay/index.md
          - Interaction scenarios: guides/mpay/interaction-scenarios.md
          - Integration development: guides/mpay/integration-development.md
          - Security: guides/mpay/security.md
          - API references: guides/mpay/api-references.md
          - Examples: guides/mpay/examples.md
          - Change log: guides/mpay/change-log.md
      - MConnect Events:
          - Overview: guides/mconnect-events/index.md
          - Interaction scenarios: guides/mconnect-events/interaction-scenarios.md
          - Integration development: guides/mconnect-events/integration-development.md
          - API references: guides/mconnect-events/api-references.md
          - Examples: guides/mconnect-events/examples.md
          - Integration libraries: guides/mconnect-events/integration-libraries.md
      - MNotify:
          - Overview: guides/mnotify/index.md
          - Steps to connect: guides/mnotify/process.md
          - Integration development: guides/mnotify/integration-development.md
          - API references: guides/mnotify/api-references.md
          - Examples: guides/mnotify/examples.md
          - Change log: guides/mnotify/change-log.md
      - MDelivery:
          - Overview: guides/mdelivery/index.md
          - Steps to connect: guides/mdelivery/process.md
          - Interaction scenarios: guides/mdelivery/interaction-scenarios.md
          - Integration development: guides/mdelivery/integration-development.md
          - API references: guides/mdelivery/api-references.md
          - Change log: guides/mdelivery/change-log.md
      - MDocs:
          - Overview: guides/mdocs/index.md
          - Steps to connect: guides/mdocs/process.md
          - Interaction scenarios: guides/mdocs/interaction-scenarios.md
          - Integration development: guides/mdocs/integration-development.md
          - API references: guides/mdocs/api-references.md
          - Security: guides/mdocs/security.md
      - MLog:
          - Overview: guides/mlog/index.md
          - Steps to connect: guides/mlog/process.md
          - Interaction scenarios: guides/mlog/interaction-scenarios.md
          - Integration development: guides/mlog/integration-development.md
          - Integration testing: guides/mlog/integration-testing.md
          - API references: guides/mlog/api-references.md
          - Examples: guides/mlog/examples.md
          - Security: guides/mlog/security.md
          - Change log: guides/mlog/change-log.md

theme:
  name: material
  logo: assets/egov-logo2.png
  favicon: assets/favicon.ico
  features:
    - navigation.sections
    - navigation.top
  palette:
    - scheme: default
      primary: indigo
      accent: purple
extra:
  social:
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/e_guvernare_moldova/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/eGovernanceAgency.Moldova
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/e-government-center
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/eGovCenterMoldova

extra_css:
  - stylesheets/extra.css
  - stylesheets/onest.css
  - stylesheets/table.css

extra_javascript:
  - js/external-links.js
  - js/nav-state.js

markdown_extensions:
  - admonition
  - pymdownx.tilde
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true

copyright: © 2010–2025 Moldova eGovernance Agency. All rights reserved.
